name: release-main

on:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node env 🏗
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: Setup pnpm 📦
        uses: pnpm/action-setup@v2
        with:
          version: 9.0.4

      - name: Install dependencies 📦
        run: pnpm install

      - name: Run linter 👀
        run: pnpm run lint-fix

      - name: Typecheck 👀
        run: pnpm run typecheck

      - name: Run tests 🧪
        run: pnpm run test:unit

      - name: Build
        run: pnpm run build

      - name: Deploy to Github Pages
        env:
          MY_EMAIL: peterrhcs@gmail.com
          MY_NAME: Narnian12
        run: |
          git config user.email $MY_EMAIL
          git config user.name $MY_NAME
          git remote set-url origin https://$MY_NAME:${{ secrets.GH_PAGES_PWD }}@github.com/narnian12/jester-website.git
          pnpm run deploy
